language: php

jobs:
    include:
        - php: 7.1
          env: SYMFONY_VERSION=3.4.* COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.2
        - php: 7.3
          env: SYMFONY_VERSION=4.4.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.4
          env: SYMFONY_VERSION=5.2.*
        - php: 8.0

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - COMPOSER_FLAGS="--prefer-dist"

before_script:
    - composer self-update
    - |
      if [ "$SYMFONY_VERSION" != "" ]; then
           sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
      fi;
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install: composer update $COMPOSER_FLAGS --no-interaction
